# Generated by Django 3.1.7 on 2021-06-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='disposable',
            field=models.BooleanField(default=False),
        ),
    ]
