# Generated by Django 3.1.7 on 2021-06-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0003_remove_url_disposable'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='temporality',
            field=models.IntegerField(default=1),
        ),
    ]
