# Generated by Django 3.1.7 on 2021-06-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0004_url_temporality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='temporality',
            field=models.IntegerField(),
        ),
    ]
