# Generated by Django 3.1.7 on 2021-06-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0007_auto_20210602_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='temporality',
        ),
    ]
