# Generated by Django 3.1.7 on 2021-06-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0008_remove_url_temporality'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='temporality',
            field=models.BooleanField(default=False),
        ),
    ]
