# Generated by Django 3.1.7 on 2021-06-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0010_auto_20210602_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='temporality',
        ),
    ]
