# Generated by Django 3.1.7 on 2021-06-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0012_auto_20210602_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='create_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='until_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
