# Generated by Django 3.1.7 on 2021-06-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0013_auto_20210603_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
