# Generated by Django 3.2.4 on 2021-06-03 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0016_alter_url_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 14, 3, 9, 943001, tzinfo=utc)),
        ),
    ]
