# Generated by Django 3.2.4 on 2021-06-03 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0022_auto_20210603_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 3, 14, 10, 41, 911837, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='until_date',
            field=models.DateField(null=True),
        ),
    ]
