# Generated by Django 3.2.4 on 2021-06-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0027_alter_url_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
