# Generated by Django 3.2.4 on 2021-06-06 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0028_alter_url_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 6, 15, 28, 39, 35329, tzinfo=utc)),
        ),
    ]
