# Generated by Django 3.2.4 on 2021-06-07 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0030_auto_20210607_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='until_date',
            new_name='expired_date',
        ),
        migrations.AlterField(
            model_name='url',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 7, 5, 35, 28, 975804, tzinfo=utc)),
        ),
    ]
