# Generated by Django 3.2.4 on 2021-06-07 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0031_auto_20210607_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='full_url',
            new_name='long_url',
        ),
        migrations.AlterField(
            model_name='url',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 7, 6, 1, 14, 883193, tzinfo=utc)),
        ),
    ]
