# Generated by Django 3.2.4 on 2021-06-07 06:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0032_auto_20210607_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 7, 6, 7, 28, 611269, tzinfo=utc)),
        ),
    ]
