# Generated by Django 3.2.4 on 2021-06-07 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0033_alter_url_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 7, 6, 56, 21, 785939, tzinfo=utc)),
        ),
    ]
