# Generated by Django 3.2.4 on 2021-06-07 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0035_alter_url_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='test_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 7, 15, 7, 50, 465419, tzinfo=utc)),
        ),
    ]
