# Generated by Django 3.2.4 on 2021-06-07 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0037_auto_20210607_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='expired_date',
        ),
        migrations.AlterField(
            model_name='url',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 7, 15, 8, 54, 714590, tzinfo=utc)),
        ),
    ]
