# Generated by Django 3.2.4 on 2021-06-08 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0038_auto_20210607_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='max_clicks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 12, 50, 34, 349704, tzinfo=utc)),
        ),
    ]
