# Generated by Django 3.2.4 on 2021-06-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0039_auto_20210608_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='pub_date',
        ),
    ]
