# Generated by Django 3.2.4 on 2021-06-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0040_remove_url_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='count_clicks',
        ),
        migrations.RemoveField(
            model_name='url',
            name='max_clicks',
        ),
    ]
